//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.FormIhm.ServiceReferencePim {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BagageDefinition", Namespace="http://schemas.datacontract.org/2004/07/MyAirport.Pim.Entities")]
    [System.SerializableAttribute()]
    public partial class BagageDefinition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeIataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompagnieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateVolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnContinuationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdBagageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItineraireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LigneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrioritaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RushField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeIata {
            get {
                return this.CodeIataField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeIataField, value) != true)) {
                    this.CodeIataField = value;
                    this.RaisePropertyChanged("CodeIata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Compagnie {
            get {
                return this.CompagnieField;
            }
            set {
                if ((object.ReferenceEquals(this.CompagnieField, value) != true)) {
                    this.CompagnieField = value;
                    this.RaisePropertyChanged("Compagnie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateVol {
            get {
                return this.DateVolField;
            }
            set {
                if ((this.DateVolField.Equals(value) != true)) {
                    this.DateVolField = value;
                    this.RaisePropertyChanged("DateVol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EnContinuation {
            get {
                return this.EnContinuationField;
            }
            set {
                if ((this.EnContinuationField.Equals(value) != true)) {
                    this.EnContinuationField = value;
                    this.RaisePropertyChanged("EnContinuation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdBagage {
            get {
                return this.IdBagageField;
            }
            set {
                if ((this.IdBagageField.Equals(value) != true)) {
                    this.IdBagageField = value;
                    this.RaisePropertyChanged("IdBagage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Itineraire {
            get {
                return this.ItineraireField;
            }
            set {
                if ((object.ReferenceEquals(this.ItineraireField, value) != true)) {
                    this.ItineraireField = value;
                    this.RaisePropertyChanged("Itineraire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ligne {
            get {
                return this.LigneField;
            }
            set {
                if ((object.ReferenceEquals(this.LigneField, value) != true)) {
                    this.LigneField = value;
                    this.RaisePropertyChanged("Ligne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Prioritaire {
            get {
                return this.PrioritaireField;
            }
            set {
                if ((this.PrioritaireField.Equals(value) != true)) {
                    this.PrioritaireField = value;
                    this.RaisePropertyChanged("Prioritaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Rush {
            get {
                return this.RushField;
            }
            set {
                if ((this.RushField.Equals(value) != true)) {
                    this.RushField = value;
                    this.RaisePropertyChanged("Rush");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePim.IServicePim")]
    public interface IServicePim {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePim/GetBagageById", ReplyAction="http://tempuri.org/IServicePim/GetBagageByIdResponse")]
        Client.FormIhm.ServiceReferencePim.BagageDefinition GetBagageById(int idBagage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePim/GetBagageById", ReplyAction="http://tempuri.org/IServicePim/GetBagageByIdResponse")]
        System.Threading.Tasks.Task<Client.FormIhm.ServiceReferencePim.BagageDefinition> GetBagageByIdAsync(int idBagage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePim/GetBagageByCodeIata", ReplyAction="http://tempuri.org/IServicePim/GetBagageByCodeIataResponse")]
        Client.FormIhm.ServiceReferencePim.BagageDefinition GetBagageByCodeIata(string codeIata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePim/GetBagageByCodeIata", ReplyAction="http://tempuri.org/IServicePim/GetBagageByCodeIataResponse")]
        System.Threading.Tasks.Task<Client.FormIhm.ServiceReferencePim.BagageDefinition> GetBagageByCodeIataAsync(string codeIata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePim/CreateBagage", ReplyAction="http://tempuri.org/IServicePim/CreateBagageResponse")]
        int CreateBagage(Client.FormIhm.ServiceReferencePim.BagageDefinition bag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePim/CreateBagage", ReplyAction="http://tempuri.org/IServicePim/CreateBagageResponse")]
        System.Threading.Tasks.Task<int> CreateBagageAsync(Client.FormIhm.ServiceReferencePim.BagageDefinition bag);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePimChannel : Client.FormIhm.ServiceReferencePim.IServicePim, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePimClient : System.ServiceModel.ClientBase<Client.FormIhm.ServiceReferencePim.IServicePim>, Client.FormIhm.ServiceReferencePim.IServicePim {
        
        public ServicePimClient() {
        }
        
        public ServicePimClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePimClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePimClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePimClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.FormIhm.ServiceReferencePim.BagageDefinition GetBagageById(int idBagage) {
            return base.Channel.GetBagageById(idBagage);
        }
        
        public System.Threading.Tasks.Task<Client.FormIhm.ServiceReferencePim.BagageDefinition> GetBagageByIdAsync(int idBagage) {
            return base.Channel.GetBagageByIdAsync(idBagage);
        }
        
        public Client.FormIhm.ServiceReferencePim.BagageDefinition GetBagageByCodeIata(string codeIata) {
            return base.Channel.GetBagageByCodeIata(codeIata);
        }
        
        public System.Threading.Tasks.Task<Client.FormIhm.ServiceReferencePim.BagageDefinition> GetBagageByCodeIataAsync(string codeIata) {
            return base.Channel.GetBagageByCodeIataAsync(codeIata);
        }
        
        public int CreateBagage(Client.FormIhm.ServiceReferencePim.BagageDefinition bag) {
            return base.Channel.CreateBagage(bag);
        }
        
        public System.Threading.Tasks.Task<int> CreateBagageAsync(Client.FormIhm.ServiceReferencePim.BagageDefinition bag) {
            return base.Channel.CreateBagageAsync(bag);
        }
    }
}
